### PR TITLE
Mf product objects

### PR DESCRIPTION
**Pull request by MeganWord**
please check content and object/array syntax- once we start writing the html/scripty stuff we'll be able to activate the keys inside the array... hopefully. not sure how that's going to work yet. 
note I didn't include any html tags in here, to simulate the format how a form is filled out by a user- we'll have to select each tag somehow in the html.

### CODE REVIEW

**Comment by josephkane** [comment]
line 35: "...hilarious gifs. gravity 40% of..."
Capitalize "gravity"

**Comment by ashwoodaa** [comment]
Line 23: link for "fuzzy planet" - you added this on the spot when I mentioned it. I'm writing it down.

Line 29: even though it looks a little odd after the list with commas I think that "really really" should be "really, really" but I may be wrong. 

Line 35: caps on "gravity". Joe already said this, again, I'm just re-writing it down for my sake.

and add final line

**Comment by MeganWord** [comment]
updates added! :)

**Comment by josephkane** [comment]
:+1:

**Comment by ashwoodaa** [comment]
:+1:

**Pull request merged**
